export // Mock table data for demonstration
const mockTableData = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    distinctId: "12345",
    updatedAt: "2024-07-08",
    countryCode: "+1",
    region: "North America",
    city: "New York",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    distinctId: "67890",
    updatedAt: "2024-07-07",
    countryCode: "+44",
    region: "Europe",
    city: "London",
  },
  {
    id: 3,
    name: "Michael Johnson",
    email: "michael.johnson@example.com",
    distinctId: "54321",
    updatedAt: "2024-07-06",
    countryCode: "+61",
    region: "Australia",
    city: "Sydney",
  },
  {
    id: 4,
    name: "Emily Brown",
    email: "emily.brown@example.com",
    distinctId: "98765",
    updatedAt: "2024-07-05",
    countryCode: "+86",
    region: "Asia",
    city: "Shanghai",
  },
  {
    id: 5,
    name: "William Davis",
    email: "william.davis@example.com",
    distinctId: "24680",
    updatedAt: "2024-07-04",
    countryCode: "+55",
    region: "South America",
    city: "São Paulo",
  },
  {
    id: 6,
    name: "Olivia Wilson",
    email: "olivia.wilson@example.com",
    distinctId: "13579",
    updatedAt: "2024-07-03",
    countryCode: "+91",
    region: "Asia",
    city: "Mumbai",
  },
  {
    id: 7,
    name: "Alexander Martinez",
    email: "alexander.martinez@example.com",
    distinctId: "11223",
    updatedAt: "2024-07-02",
    countryCode: "+52",
    region: "North America",
    city: "Mexico City",
  },
  {
    id: 8,
    name: "Sophia Rodriguez",
    email: "sophia.rodriguez@example.com",
    distinctId: "44556",
    updatedAt: "2024-07-01",
    countryCode: "+33",
    region: "Europe",
    city: "Paris",
  },
  {
    id: 9,
    name: "Ethan Thompson",
    email: "ethan.thompson@example.com",
    distinctId: "77889",
    updatedAt: "2024-06-30",
    countryCode: "+81",
    region: "Asia",
    city: "Tokyo",
  },
  {
    id: 10,
    name: "Isabella White",
    email: "isabella.white@example.com",
    distinctId: "99000",
    updatedAt: "2024-06-29",
    countryCode: "+61",
    region: "Australia",
    city: "Melbourne",
  },
];
