import React from "react";

const Application = () => {
  return (
    <svg
      width={24}
      height={24}
      color="white"
      data-name="Layer 1"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 22 22"
    >
      <rect
        x="3"
        y="3"
        width="3.2"
        height="3.2"
        rx=".8"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="6%"
      ></rect>
      <rect
        x="15.8"
        y="3"
        width="3.2"
        height="3.2"
        rx=".8"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="6%"
      ></rect>
      <rect
        x="9.4"
        y="3"
        width="3.2"
        height="3.2"
        rx=".8"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="6%"
      ></rect>
      <rect
        x="3"
        y="9.4"
        width="3.2"
        height="3.2"
        rx=".8"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="6%"
      ></rect>
      <rect
        x="15.8"
        y="9.4"
        width="3.2"
        height="3.2"
        rx=".8"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="6%"
      ></rect>
      <rect
        x="9.4"
        y="9.4"
        width="3.2"
        height="3.2"
        rx=".8"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="6%"
      ></rect>
      <rect
        x="3"
        y="15.8"
        width="3.2"
        height="3.2"
        rx=".8"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="6%"
      ></rect>
      <rect
        x="15.8"
        y="15.8"
        width="3.2"
        height="3.2"
        rx=".8"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="6%"
      ></rect>
      <rect
        x="9.4"
        y="15.8"
        width="3.2"
        height="3.2"
        rx=".8"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="6%"
      ></rect>
    </svg>
  );
};

export default Application;
